// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(2),  /* key_lit */
			shift(3),  /* add_lit */
			shift(4),  /* true */
			shift(5),  /* false */
			shift(6),  /* nat_lit */
			shift(7),  /* koin_lit */
			shift(8),  /* int_lit */
			shift(9),  /* string_lit */
			shift(10), /* () */
			shift(14), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(15), /* [ */
			nil,       /* ] */
			shift(16), /* [] */
			nil,       /* ; */
			shift(17), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* key_lit */
			nil,          /* add_lit */
			nil,          /* true */
			nil,          /* false */
			nil,          /* nat_lit */
			nil,          /* koin_lit */
			nil,          /* int_lit */
			nil,          /* string_lit */
			nil,          /* () */
			nil,          /* ( */
			nil,          /* ) */
			nil,          /* , */
			nil,          /* [ */
			nil,          /* ] */
			nil,          /* [] */
			nil,          /* ; */
			nil,          /* { */
			nil,          /* } */
			nil,          /* lident */
			nil,          /* = */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(7), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(8), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: Constant */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: Constant */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: Constant */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(12), /* $, reduce: Constant */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* key_lit */
			shift(20), /* add_lit */
			shift(21), /* true */
			shift(22), /* false */
			shift(23), /* nat_lit */
			shift(24), /* koin_lit */
			shift(25), /* int_lit */
			shift(26), /* string_lit */
			shift(27), /* () */
			shift(31), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(33), /* [ */
			nil,       /* ] */
			shift(34), /* [] */
			nil,       /* ; */
			shift(35), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(17), /* $, reduce: List */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			shift(56), /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(1), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(2), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(3), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(4), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(5), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(6), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(7), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(8), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			reduce(9), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(10), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(11), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(12), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* key_lit */
			shift(20), /* add_lit */
			shift(21), /* true */
			shift(22), /* false */
			shift(23), /* nat_lit */
			shift(24), /* koin_lit */
			shift(25), /* int_lit */
			shift(26), /* string_lit */
			shift(27), /* () */
			shift(31), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(33), /* [ */
			nil,       /* ] */
			shift(34), /* [] */
			nil,       /* ; */
			shift(35), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			shift(58), /* ) */
			shift(59), /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(17), /* ,, reduce: List */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(18), /* ], reduce: List1 */
			nil,        /* [] */
			reduce(18), /* ;, reduce: List1 */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(1), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(1), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(2), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(2), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(3), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(3), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(4), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(4), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(5), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(5), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(6), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(6), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(7), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(7), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(8), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(8), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			reduce(9), /* ], reduce: Constant */
			nil,       /* [] */
			reduce(9), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(10), /* ], reduce: Constant */
			nil,        /* [] */
			reduce(10), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(11), /* ], reduce: Constant */
			nil,        /* [] */
			reduce(11), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(12), /* ], reduce: Constant */
			nil,        /* [] */
			reduce(12), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* key_lit */
			shift(20), /* add_lit */
			shift(21), /* true */
			shift(22), /* false */
			shift(23), /* nat_lit */
			shift(24), /* koin_lit */
			shift(25), /* int_lit */
			shift(26), /* string_lit */
			shift(27), /* () */
			shift(31), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(33), /* [ */
			nil,       /* ] */
			shift(34), /* [] */
			nil,       /* ; */
			shift(35), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			shift(64), /* ] */
			nil,       /* [] */
			shift(65), /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(17), /* ], reduce: List */
			nil,        /* [] */
			reduce(17), /* ;, reduce: List */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			shift(67), /* } */
			shift(68), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			shift(69), /* = */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(71), /* key_lit */
			shift(72), /* add_lit */
			shift(73), /* true */
			shift(74), /* false */
			shift(75), /* nat_lit */
			shift(76), /* koin_lit */
			shift(77), /* int_lit */
			shift(78), /* string_lit */
			shift(79), /* () */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(84), /* [ */
			nil,       /* ] */
			shift(85), /* [] */
			nil,       /* ; */
			shift(86), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			shift(87), /* ) */
			shift(59), /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(13), /* $, reduce: Tuple */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(71), /* key_lit */
			shift(72), /* add_lit */
			shift(73), /* true */
			shift(74), /* false */
			shift(75), /* nat_lit */
			shift(76), /* koin_lit */
			shift(77), /* int_lit */
			shift(78), /* string_lit */
			shift(79), /* () */
			shift(83), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(84), /* [ */
			nil,       /* ] */
			shift(85), /* [] */
			nil,       /* ; */
			shift(86), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			shift(89), /* ] */
			nil,       /* [] */
			shift(65), /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			shift(90), /* } */
			shift(68), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			shift(91), /* ) */
			shift(59), /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			shift(92), /* ] */
			nil,       /* [] */
			shift(65), /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(16), /* $, reduce: List */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			shift(94), /* } */
			shift(68), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(20), /* $, reduce: Struct */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			shift(95), /* = */
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			shift(97),  /* key_lit */
			shift(98),  /* add_lit */
			shift(99),  /* true */
			shift(100), /* false */
			shift(101), /* nat_lit */
			shift(102), /* koin_lit */
			shift(103), /* int_lit */
			shift(104), /* string_lit */
			shift(105), /* () */
			shift(109), /* ( */
			nil,        /* ) */
			nil,        /* , */
			shift(110), /* [ */
			nil,        /* ] */
			shift(111), /* [] */
			nil,        /* ; */
			shift(112), /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(15), /* ), reduce: Tuple1 */
			reduce(15), /* ,, reduce: Tuple1 */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(1), /* ), reduce: Constant */
			reduce(1), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(2), /* ), reduce: Constant */
			reduce(2), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(3), /* ), reduce: Constant */
			reduce(3), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(4), /* ), reduce: Constant */
			reduce(4), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(5), /* ), reduce: Constant */
			reduce(5), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(6), /* ), reduce: Constant */
			reduce(6), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(7), /* ), reduce: Constant */
			reduce(7), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(8), /* ), reduce: Constant */
			reduce(8), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			reduce(9), /* ), reduce: Constant */
			reduce(9), /* ,, reduce: Constant */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(10), /* ), reduce: Constant */
			reduce(10), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(11), /* ), reduce: Constant */
			reduce(11), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(12), /* ), reduce: Constant */
			reduce(12), /* ,, reduce: Constant */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* key_lit */
			shift(20), /* add_lit */
			shift(21), /* true */
			shift(22), /* false */
			shift(23), /* nat_lit */
			shift(24), /* koin_lit */
			shift(25), /* int_lit */
			shift(26), /* string_lit */
			shift(27), /* () */
			shift(31), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(33), /* [ */
			nil,       /* ] */
			shift(34), /* [] */
			nil,       /* ; */
			shift(35), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(17), /* ), reduce: List */
			reduce(17), /* ,, reduce: List */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(13), /* ,, reduce: Tuple */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(14), /* ), reduce: Tuple1 */
			reduce(14), /* ,, reduce: Tuple1 */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(16), /* ,, reduce: List */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			reduce(20), /* ,, reduce: Struct */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(13), /* ], reduce: Tuple */
			nil,        /* [] */
			reduce(13), /* ;, reduce: Tuple */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(16), /* ], reduce: List */
			nil,        /* [] */
			reduce(16), /* ;, reduce: List */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(19), /* ], reduce: List1 */
			nil,        /* [] */
			reduce(19), /* ;, reduce: List1 */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			reduce(20), /* ], reduce: Struct */
			nil,        /* [] */
			reduce(20), /* ;, reduce: Struct */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			shift(97),  /* key_lit */
			shift(98),  /* add_lit */
			shift(99),  /* true */
			shift(100), /* false */
			shift(101), /* nat_lit */
			shift(102), /* koin_lit */
			shift(103), /* int_lit */
			shift(104), /* string_lit */
			shift(105), /* () */
			shift(109), /* ( */
			nil,        /* ) */
			nil,        /* , */
			shift(110), /* [ */
			nil,        /* ] */
			shift(111), /* [] */
			nil,        /* ; */
			shift(112), /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			shift(117), /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(1), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(2), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(3), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(4), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(5), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(6), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(7), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(8), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			reduce(9), /* ;, reduce: Constant */
			nil,       /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(10), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(11), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(12), /* ;, reduce: Constant */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(19), /* key_lit */
			shift(20), /* add_lit */
			shift(21), /* true */
			shift(22), /* false */
			shift(23), /* nat_lit */
			shift(24), /* koin_lit */
			shift(25), /* int_lit */
			shift(26), /* string_lit */
			shift(27), /* () */
			shift(31), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(33), /* [ */
			nil,       /* ] */
			shift(34), /* [] */
			nil,       /* ; */
			shift(35), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			shift(37), /* key_lit */
			shift(38), /* add_lit */
			shift(39), /* true */
			shift(40), /* false */
			shift(41), /* nat_lit */
			shift(42), /* koin_lit */
			shift(43), /* int_lit */
			shift(44), /* string_lit */
			shift(45), /* () */
			shift(49), /* ( */
			nil,       /* ) */
			nil,       /* , */
			shift(50), /* [ */
			nil,       /* ] */
			shift(52), /* [] */
			nil,       /* ; */
			shift(53), /* { */
			nil,       /* } */
			nil,       /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(17), /* ;, reduce: List */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* key_lit */
			nil,       /* add_lit */
			nil,       /* true */
			nil,       /* false */
			nil,       /* nat_lit */
			nil,       /* koin_lit */
			nil,       /* int_lit */
			nil,       /* string_lit */
			nil,       /* () */
			nil,       /* ( */
			nil,       /* ) */
			nil,       /* , */
			nil,       /* [ */
			nil,       /* ] */
			nil,       /* [] */
			nil,       /* ; */
			nil,       /* { */
			nil,       /* } */
			shift(55), /* lident */
			nil,       /* = */
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			shift(121), /* ) */
			shift(59),  /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			shift(122), /* ] */
			nil,        /* [] */
			shift(65),  /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			shift(123), /* } */
			shift(68),  /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			shift(124), /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			reduce(21), /* }, reduce: Struct1 */
			reduce(21), /* lident, reduce: Struct1 */
			nil,        /* = */
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			shift(125), /* ) */
			shift(59),  /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			shift(126), /* ] */
			nil,        /* [] */
			shift(65),  /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			shift(127), /* } */
			shift(68),  /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(13), /* ), reduce: Tuple */
			reduce(13), /* ,, reduce: Tuple */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(16), /* ), reduce: List */
			reduce(16), /* ,, reduce: List */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			reduce(20), /* ), reduce: Struct */
			reduce(20), /* ,, reduce: Struct */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			nil,        /* ; */
			nil,        /* { */
			reduce(22), /* }, reduce: Struct1 */
			reduce(22), /* lident, reduce: Struct1 */
			nil,        /* = */
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(13), /* ;, reduce: Tuple */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(16), /* ;, reduce: List */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
	actionRow{ // S127
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* key_lit */
			nil,        /* add_lit */
			nil,        /* true */
			nil,        /* false */
			nil,        /* nat_lit */
			nil,        /* koin_lit */
			nil,        /* int_lit */
			nil,        /* string_lit */
			nil,        /* () */
			nil,        /* ( */
			nil,        /* ) */
			nil,        /* , */
			nil,        /* [ */
			nil,        /* ] */
			nil,        /* [] */
			reduce(20), /* ;, reduce: Struct */
			nil,        /* { */
			nil,        /* } */
			nil,        /* lident */
			nil,        /* = */
		},
	},
}
