// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 8

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Constant
		11, // Tuple
		-1, // Tuple1
		12, // List
		-1, // List1
		13, // Struct
		-1, // Struct1
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S14
		-1, // S'
		18, // Constant
		28, // Tuple
		32, // Tuple1
		29, // List
		-1, // List1
		30, // Struct
		-1, // Struct1
	},
	gotoRow{ // S15
		-1, // S'
		36, // Constant
		46, // Tuple
		-1, // Tuple1
		47, // List
		51, // List1
		48, // Struct
		-1, // Struct1
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		54, // Struct1
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S25
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S26
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S27
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S28
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S29
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S30
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S31
		-1, // S'
		18, // Constant
		28, // Tuple
		57, // Tuple1
		29, // List
		-1, // List1
		30, // Struct
		-1, // Struct1
	},
	gotoRow{ // S32
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S33
		-1, // S'
		36, // Constant
		46, // Tuple
		-1, // Tuple1
		47, // List
		60, // List1
		48, // Struct
		-1, // Struct1
	},
	gotoRow{ // S34
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S35
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		61, // Struct1
	},
	gotoRow{ // S36
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S37
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S38
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S39
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S40
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S41
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S42
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S43
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S44
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S45
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S46
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S47
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S48
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S49
		-1, // S'
		18, // Constant
		28, // Tuple
		62, // Tuple1
		29, // List
		-1, // List1
		30, // Struct
		-1, // Struct1
	},
	gotoRow{ // S50
		-1, // S'
		36, // Constant
		46, // Tuple
		-1, // Tuple1
		47, // List
		63, // List1
		48, // Struct
		-1, // Struct1
	},
	gotoRow{ // S51
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S52
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S53
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		66, // Struct1
	},
	gotoRow{ // S54
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S55
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S56
		-1, // S'
		70, // Constant
		80, // Tuple
		-1, // Tuple1
		81, // List
		-1, // List1
		82, // Struct
		-1, // Struct1
	},
	gotoRow{ // S57
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S58
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S59
		-1, // S'
		88, // Constant
		80, // Tuple
		-1, // Tuple1
		81, // List
		-1, // List1
		82, // Struct
		-1, // Struct1
	},
	gotoRow{ // S60
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S61
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S62
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S63
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S64
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S65
		-1, // S'
		93, // Constant
		46, // Tuple
		-1, // Tuple1
		47, // List
		-1, // List1
		48, // Struct
		-1, // Struct1
	},
	gotoRow{ // S66
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S67
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S68
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S69
		-1,  // S'
		96,  // Constant
		106, // Tuple
		-1,  // Tuple1
		107, // List
		-1,  // List1
		108, // Struct
		-1,  // Struct1
	},
	gotoRow{ // S70
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S71
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S72
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S73
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S74
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S75
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S76
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S77
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S78
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S79
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S80
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S81
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S82
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S83
		-1,  // S'
		18,  // Constant
		28,  // Tuple
		113, // Tuple1
		29,  // List
		-1,  // List1
		30,  // Struct
		-1,  // Struct1
	},
	gotoRow{ // S84
		-1,  // S'
		36,  // Constant
		46,  // Tuple
		-1,  // Tuple1
		47,  // List
		114, // List1
		48,  // Struct
		-1,  // Struct1
	},
	gotoRow{ // S85
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S86
		-1,  // S'
		-1,  // Constant
		-1,  // Tuple
		-1,  // Tuple1
		-1,  // List
		-1,  // List1
		-1,  // Struct
		115, // Struct1
	},
	gotoRow{ // S87
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S88
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S89
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S90
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S91
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S92
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S93
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S94
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S95
		-1,  // S'
		116, // Constant
		106, // Tuple
		-1,  // Tuple1
		107, // List
		-1,  // List1
		108, // Struct
		-1,  // Struct1
	},
	gotoRow{ // S96
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S97
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S98
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S99
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S100
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S101
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S102
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S103
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S104
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S105
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S106
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S107
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S108
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S109
		-1,  // S'
		18,  // Constant
		28,  // Tuple
		118, // Tuple1
		29,  // List
		-1,  // List1
		30,  // Struct
		-1,  // Struct1
	},
	gotoRow{ // S110
		-1,  // S'
		36,  // Constant
		46,  // Tuple
		-1,  // Tuple1
		47,  // List
		119, // List1
		48,  // Struct
		-1,  // Struct1
	},
	gotoRow{ // S111
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S112
		-1,  // S'
		-1,  // Constant
		-1,  // Tuple
		-1,  // Tuple1
		-1,  // List
		-1,  // List1
		-1,  // Struct
		120, // Struct1
	},
	gotoRow{ // S113
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S114
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S115
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S116
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S117
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S118
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S119
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S120
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S121
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S122
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S123
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S124
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S125
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S126
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
	gotoRow{ // S127
		-1, // S'
		-1, // Constant
		-1, // Tuple
		-1, // Tuple1
		-1, // List
		-1, // List1
		-1, // Struct
		-1, // Struct1
	},
}
