// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 38: // ['&','&']
			return 3
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 42: // ['*','*']
			return 6
		case r == 43: // ['+','+']
			return 7
		case r == 44: // [',',',']
			return 8
		case r == 45: // ['-','-']
			return 9
		case r == 46: // ['.','.']
			return 10
		case r == 47: // ['/','/']
			return 11
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		case r == 58: // [':',':']
			return 13
		case r == 59: // [';',';']
			return 14
		case r == 60: // ['<','<']
			return 15
		case r == 61: // ['=','=']
			return 16
		case r == 62: // ['>','>']
			return 17
		case 65 <= r && r <= 90: // ['A','Z']
			return 18
		case r == 91: // ['[','[']
			return 19
		case r == 93: // [']',']']
			return 20
		case r == 95: // ['_','_']
			return 21
		case r == 97: // ['a','a']
			return 22
		case r == 98: // ['b','b']
			return 23
		case 99 <= r && r <= 100: // ['c','d']
			return 21
		case r == 101: // ['e','e']
			return 24
		case r == 102: // ['f','f']
			return 25
		case 103 <= r && r <= 104: // ['g','h']
			return 21
		case r == 105: // ['i','i']
			return 26
		case r == 106: // ['j','j']
			return 21
		case r == 107: // ['k','k']
			return 27
		case r == 108: // ['l','l']
			return 28
		case r == 109: // ['m','m']
			return 21
		case r == 110: // ['n','n']
			return 29
		case r == 111: // ['o','o']
			return 30
		case 112 <= r && r <= 114: // ['p','r']
			return 21
		case r == 115: // ['s','s']
			return 31
		case r == 116: // ['t','t']
			return 32
		case r == 117: // ['u','u']
			return 33
		case 118 <= r && r <= 122: // ['v','z']
			return 21
		case r == 123: // ['{','{']
			return 34
		case r == 124: // ['|','|']
			return 35
		case r == 125: // ['}','}']
			return 36
		case r == 126: // ['~','~']
			return 37
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 38
		default:
			return 2
		}
	},
	// S3
	func(r rune) int {
		switch {
		case r == 38: // ['&','&']
			return 39
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 40
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 41
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 43
		case 48 <= r && r <= 57: // ['0','9']
			return 12
		case r == 107: // ['k','k']
			return 44
		case r == 112: // ['p','p']
			return 45
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 58: // [':',':']
			return 46
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 47
		case r == 61: // ['=','=']
			return 48
		case r == 62: // ['>','>']
			return 49
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 50
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case 65 <= r && r <= 90: // ['A','Z']
			return 51
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 51
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 52
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 99: // ['a','c']
			return 53
		case r == 100: // ['d','d']
			return 54
		case 101 <= r && r <= 122: // ['e','z']
			return 53
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 110: // ['a','n']
			return 53
		case r == 111: // ['o','o']
			return 55
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 107: // ['a','k']
			return 53
		case r == 108: // ['l','l']
			return 56
		case 109 <= r && r <= 122: // ['m','z']
			return 53
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case r == 97: // ['a','a']
			return 57
		case 98 <= r && r <= 122: // ['b','z']
			return 53
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 101: // ['a','e']
			return 53
		case r == 102: // ['f','f']
			return 58
		case 103 <= r && r <= 109: // ['g','m']
			return 53
		case r == 110: // ['n','n']
			return 59
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 60
		case 102 <= r && r <= 109: // ['f','m']
			return 53
		case r == 110: // ['n','n']
			return 61
		case r == 111: // ['o','o']
			return 62
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case r == 97: // ['a','a']
			return 63
		case 98 <= r && r <= 100: // ['b','d']
			return 53
		case r == 101: // ['e','e']
			return 64
		case 102 <= r && r <= 104: // ['f','h']
			return 53
		case r == 105: // ['i','i']
			return 65
		case 106 <= r && r <= 110: // ['j','n']
			return 53
		case r == 111: // ['o','o']
			return 66
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case r == 97: // ['a','a']
			return 67
		case 98 <= r && r <= 110: // ['b','n']
			return 53
		case r == 111: // ['o','o']
			return 68
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 111: // ['a','o']
			return 53
		case r == 112: // ['p','p']
			return 69
		case r == 113: // ['q','q']
			return 53
		case r == 114: // ['r','r']
			return 70
		case 115 <= r && r <= 122: // ['s','z']
			return 53
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 71
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 103: // ['a','g']
			return 53
		case r == 104: // ['h','h']
			return 72
		case 105 <= r && r <= 113: // ['i','q']
			return 53
		case r == 114: // ['r','r']
			return 73
		case 115 <= r && r <= 120: // ['s','x']
			return 53
		case r == 121: // ['y','y']
			return 74
		case r == 122: // ['z','z']
			return 53
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 75
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 124: // ['|','|']
			return 76
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 77
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 78
		default:
			return 40
		}
	},
	// S41
	func(r rune) int {
		switch {
		case r == 45: // ['-','-']
			return 41
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 42
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 80
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 51
		case 65 <= r && r <= 90: // ['A','Z']
			return 51
		case r == 95: // ['_','_']
			return 51
		case 97 <= r && r <= 122: // ['a','z']
			return 51
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 81
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 99: // ['a','c']
			return 53
		case r == 100: // ['d','d']
			return 82
		case 101 <= r && r <= 122: // ['e','z']
			return 53
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 110: // ['a','n']
			return 53
		case r == 111: // ['o','o']
			return 83
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 114: // ['a','r']
			return 53
		case r == 115: // ['s','s']
			return 84
		case 116 <= r && r <= 122: // ['t','z']
			return 53
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 107: // ['a','k']
			return 53
		case r == 108: // ['l','l']
			return 85
		case 109 <= r && r <= 122: // ['m','z']
			return 53
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 86
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 120: // ['a','x']
			return 53
		case r == 121: // ['y','y']
			return 87
		case r == 122: // ['z','z']
			return 53
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case r == 48: // ['0','0']
			return 53
		case r == 49: // ['1','1']
			return 88
		case r == 50: // ['2','2']
			return 89
		case 51 <= r && r <= 57: // ['3','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 104: // ['a','h']
			return 53
		case r == 105: // ['i','i']
			return 90
		case 106 <= r && r <= 122: // ['j','z']
			return 53
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 91
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 92
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 114: // ['a','r']
			return 53
		case r == 115: // ['s','s']
			return 93
		case 116 <= r && r <= 122: // ['t','z']
			return 53
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 113: // ['a','q']
			return 53
		case r == 114: // ['r','r']
			return 70
		case 115 <= r && r <= 122: // ['s','z']
			return 53
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 94
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 95
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 96
		case 102 <= r && r <= 115: // ['f','s']
			return 53
		case r == 116: // ['t','t']
			return 97
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 113: // ['a','q']
			return 53
		case r == 114: // ['r','r']
			return 98
		case 115 <= r && r <= 122: // ['s','z']
			return 53
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 99
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 116: // ['a','t']
			return 53
		case r == 117: // ['u','u']
			return 100
		case 118 <= r && r <= 122: // ['v','z']
			return 53
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 111: // ['a','o']
			return 53
		case r == 112: // ['p','p']
			return 101
		case 113 <= r && r <= 122: // ['q','z']
			return 53
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 104: // ['a','h']
			return 53
		case r == 105: // ['i','i']
			return 102
		case 106 <= r && r <= 122: // ['j','z']
			return 53
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case r == 41: // [')',')']
			return 103
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 79
		case r == 107: // ['k','k']
			return 104
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case r == 118: // ['v','v']
			return 105
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 113: // ['a','q']
			return 53
		case r == 114: // ['r','r']
			return 106
		case 115 <= r && r <= 122: // ['s','z']
			return 53
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 107: // ['a','k']
			return 53
		case r == 108: // ['l','l']
			return 107
		case 109 <= r && r <= 122: // ['m','z']
			return 53
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 108
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 114: // ['a','r']
			return 53
		case r == 115: // ['s','s']
			return 109
		case 116 <= r && r <= 122: // ['t','z']
			return 53
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 110
		case 103 <= r && r <= 122: // ['g','z']
			return 53
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 111
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 111
		case 103 <= r && r <= 122: // ['g','z']
			return 53
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 112
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 99: // ['a','c']
			return 53
		case r == 100: // ['d','d']
			return 113
		case 101 <= r && r <= 122: // ['e','z']
			return 53
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case r == 37: // ['%','%']
			return 114
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S93
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 115
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S94
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S95
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S96
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 113: // ['a','q']
			return 53
		case r == 114: // ['r','r']
			return 116
		case 115 <= r && r <= 122: // ['s','z']
			return 53
		}
		return NoState
	},
	// S97
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 104: // ['a','h']
			return 53
		case r == 105: // ['i','i']
			return 117
		case 106 <= r && r <= 122: // ['j','z']
			return 53
		}
		return NoState
	},
	// S98
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 104: // ['a','h']
			return 53
		case r == 105: // ['i','i']
			return 118
		case 106 <= r && r <= 122: // ['j','z']
			return 53
		}
		return NoState
	},
	// S99
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 119
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S100
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 120
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S101
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 121
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S102
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 122
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S103
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S104
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 80
		}
		return NoState
	},
	// S105
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 123
		}
		return NoState
	},
	// S106
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 124
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S107
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S108
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S109
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 100: // ['a','d']
			return 53
		case r == 101: // ['e','e']
			return 125
		case 102 <= r && r <= 122: // ['f','z']
			return 53
		}
		return NoState
	},
	// S110
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 110
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 110
		case 103 <= r && r <= 122: // ['g','z']
			return 53
		}
		return NoState
	},
	// S111
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 111
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 111
		case 103 <= r && r <= 122: // ['g','z']
			return 53
		}
		return NoState
	},
	// S112
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S113
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S114
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 126
		case r == 105: // ['i','i']
			return 127
		}
		return NoState
	},
	// S115
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S116
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case r == 97: // ['a','a']
			return 128
		case 98 <= r && r <= 122: // ['b','z']
			return 53
		}
		return NoState
	},
	// S117
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 110: // ['a','n']
			return 53
		case r == 111: // ['o','o']
			return 129
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S118
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 130
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S119
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S120
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S121
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S122
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S123
	func(r rune) int {
		switch {
		case r == 114: // ['r','r']
			return 131
		}
		return NoState
	},
	// S124
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 114: // ['a','r']
			return 53
		case r == 115: // ['s','s']
			return 132
		case 116 <= r && r <= 122: // ['t','z']
			return 53
		}
		return NoState
	},
	// S125
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S126
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 133
		}
		return NoState
	},
	// S127
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 134
		}
		return NoState
	},
	// S128
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 115: // ['a','s']
			return 53
		case r == 116: // ['t','t']
			return 135
		case 117 <= r && r <= 122: // ['u','z']
			return 53
		}
		return NoState
	},
	// S129
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 136
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S130
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 102: // ['a','f']
			return 53
		case r == 103: // ['g','g']
			return 137
		case 104 <= r && r <= 122: // ['h','z']
			return 53
		}
		return NoState
	},
	// S131
	func(r rune) int {
		switch {
		case r == 115: // ['s','s']
			return 138
		}
		return NoState
	},
	// S132
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 114: // ['a','r']
			return 53
		case r == 115: // ['s','s']
			return 139
		case 116 <= r && r <= 122: // ['t','z']
			return 53
		}
		return NoState
	},
	// S133
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 140
		}
		return NoState
	},
	// S134
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 141
		}
		return NoState
	},
	// S135
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 104: // ['a','h']
			return 53
		case r == 105: // ['i','i']
			return 142
		case 106 <= r && r <= 122: // ['j','z']
			return 53
		}
		return NoState
	},
	// S136
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S137
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S138
	func(r rune) int {
		switch {
		case r == 105: // ['i','i']
			return 143
		}
		return NoState
	},
	// S139
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S140
	func(r rune) int {
		switch {
		case r == 114: // ['r','r']
			return 144
		}
		return NoState
	},
	// S141
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 145
		}
		return NoState
	},
	// S142
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 110: // ['a','n']
			return 53
		case r == 111: // ['o','o']
			return 146
		case 112 <= r && r <= 122: // ['p','z']
			return 53
		}
		return NoState
	},
	// S143
	func(r rune) int {
		switch {
		case r == 111: // ['o','o']
			return 147
		}
		return NoState
	},
	// S144
	func(r rune) int {
		switch {
		case r == 121: // ['y','y']
			return 148
		}
		return NoState
	},
	// S145
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S146
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 109: // ['a','m']
			return 53
		case r == 110: // ['n','n']
			return 149
		case 111 <= r && r <= 122: // ['o','z']
			return 53
		}
		return NoState
	},
	// S147
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 150
		}
		return NoState
	},
	// S148
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S149
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 53
		case 65 <= r && r <= 90: // ['A','Z']
			return 53
		case r == 95: // ['_','_']
			return 53
		case 97 <= r && r <= 122: // ['a','z']
			return 53
		}
		return NoState
	},
	// S150
	func(r rune) int {
		switch {
		case r == 32: // [' ',' ']
			return 151
		}
		return NoState
	},
	// S151
	func(r rune) int {
		switch {
		case r == 93: // [']',']']
			return 152
		default:
			return 151
		}
	},
	// S152
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
